# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f69af58048deeae3630c43ac970cd56b84e045e0982dfae96e73132e21ac827f418e008323bcfbd4086f6cc53402cb6d701b136f56fd89282c1235d633ffc9d

test:
  secret_key_base: 30d76c389a2d7a1c1eeb7db234ff4986672efa5bef7b99d665332b3fd6c3ba7e2810df371e25eb76c7f6350a964f97a71891944da0dc0e7737f509da15986f5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
